version: "3"

services:
  mysql:
    image: mysql:8.0.23
    container_name: ${DB_HOST_NAME}
    hostname: ${DB_HOST_NAME}
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    image: drupal:php7.4-fpm-alpine
    container_name: drupal.m5l
    hostname: drupal.m5l
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver.m5l
    hostname: webserver.m5l
    depends_on:
      - drupal
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
      - ./nginx-drupal.conf:/etc/nginx/conf.d/nginx.conf
      - certbot-etc:/etc/letsencrypt
    networks:
      - external

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - drupal-data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --staging -d your_domain -d www.your_domain

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data:
  db-data:
  certbot-etc: