version: "3"

services:
  mysql:
    image: mysql:5.7.33
    container_name: mysql.m5l
    hostname: mysql.m5l
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_m5l_drupal_1
      MYSQL_ROOT_PASSWORD: mySQLm5l
      MYSQL_USER: drupaluser_m5l
      MYSQL_PASSWORD: mySQLm5l
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - internal

  m5l-root:
    build:
      context: ./m5l-container
      dockerfile: ./m5l.dockerfile
    container_name: m5l-root.m5l
    hostname: m5l-root.m5l
    tty: true
    depends_on:
      - mysql
      - drupal
    networks:
      - internal
    volumes:
      - /widen/m5l-data:/m5l-data:z
      - /root/m5l-source:/m5l-source:z
      - ./m5l-container/m5l-responder.py:/m5l-responder.py
      # entry point for exchange cases between drupal and m5l
      - /root/m5l/drupal-data/sites/default/files/tmp-CAD-local:/m5l-data/drupal/tmp-CAD-local/:z
    entrypoint: python3 /m5l-responder.py "/m5l-source/magic5-src/runCAD.sh"


  drupal:
    build:
      context: ./drupal-container
      dockerfile: ./drupal.dockerfile
    container_name: drupal.m5l
    hostname: drupal.m5l
    depends_on:
      - mysql
    networks:
      - internal
      - external
    volumes:
      - ./drupal-data:/var/www/html:z
      - ./sendmail-data:/etc/mail:z
    command: bash -c "yes | sendmailconfig && sendmail -bD & docker-php-entrypoint php-fpm"
    tty: true

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver.m5l
    hostname: webserver.m5l
    depends_on:
      - drupal
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./drupal-data:/var/www/html:z
      - /root/certs:/certs
      - ./nginx-drupal7.conf.2:/etc/nginx/conf.d/default.conf
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge