version: "3.3"
services:
  drupal7:
    image: "drupal:7.78-php7.4-apache"
    container_name: drupal7.m5l
    hostname: drupal7.m5l
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - mysql
    links:
      - "mysql:mysql.m5l"
    volumes:
      - ./drupal-data:/var/www/html
      - "./settings.php:/tmp/settings.php"
  
  mysql:
    image: "mysql:8.0.23"
    container_name: mysql.m5l
    hostname: mysql.m5l
    environment: 
      - MYSQL_DATABASE="db_m5l_drupal_1"
      - MYSQL_ROOT_PASSWORD="mySQLm5l"
      - MYSQL_USER="drupaluser_m5l"
      - MYSQL_PASSWORD="mySQLm5l"
  
  certbot:
    depends_on:
      - drupal7
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./drupal-data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email cerello@to.infn.it --agree-tos --no-eff-email --staging -d m5l.to.infn.it -d www.m5l.to.infn.it