version: "3.3"
services:
  mysql:
    image: mysql:8.0.23
    container_name: ${DB_HOST_NAME}
    hostname: ${DB_HOST_NAME}
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - internal

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    container_name: pma.m5l
    hostname: pma.m5l
    environment:
      PMA_HOST: ${DB_HOST_NAME}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    depends_on:
      - mysql
    ports:
      - '81:80'
    networks:
      - internal
      - external

  drupal:
    image: drupal:7.78-php7.4
    container_name: drupal.m5l
    hostname: drupal.m5l
    depends_on: 
      - mysql
    ports:
      - '8080:80'
    volumes:
      - ./drupal-data:/var/www/html
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
      - ./settings.php:/tmp/settings.php
    environment: 
      DRUPAL_DATABASE_HOST: ${DB_HOST_NAME}
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: ${DB_NAME}
      DRUPAL_DATABASE_USERNAME: ${DB_USERNAME}
      DRUPAL_DATABASE_PASSWORD: ${DB_PASSWORD}
      DRUPAL_HASH_SALT: db0de8a1556ba5348f87cfc992cd2c9641713d46e9412c8b05
    networks:
      - internal
      - external

  httpd:
    image: bitnami/apache:latest
    container_name: httpd.m5l
    hostname: httpd.m5l
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - drupal
    volumes:
      - ./drupal-data:/drupal-data
      # - ./apache-drupal-certs:/certs
      - ./apache-drupal.conf:/vhosts/my_vhost.conf:ro
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data: