version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql.m5l
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_m5l_drupal_1
      MYSQL_ROOT_PASSWORD: mySQLm5l
      MYSQL_USER: drupaluser_m5l
      MYSQL_PASSWORD: mySQLm5l
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    # image: drupal:7.78-php7.4-fpm-alpine3.12
    build: ./drupal-m5l.dockerfile
    container_name: drupal.m5l
    depends_on:
      - mysql
    networks:
      - internal
      - external
    volumes:
      - ./drupal-data:/var/www/html:z

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver.m5l
    depends_on:
      - drupal
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./drupal-data:/var/www/html:ro
      - ./certs:/certs
      - ./nginx-drupal7.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge